name: Test SSH vers Alwaysdata

on:
  workflow_dispatch:

jobs:
  TestSSH:
    runs-on: ubuntu-latest
    steps:
      - name: Connexion SSH avec clé privée via secret
        uses: appleboy/ssh-action@master
        with:
          host: "ssh-${{ secrets.USERNAME }}.alwaysdata.net"
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "Connexion réussie à Alwaysdata !"
            hostname
            ls -al $HOME/www
